name: erosta_loans
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dotted_line: ^3.1.0
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dotted_border: ^2.0.0+2
  flutter_svg: ^2.0.7
  flutter_svg_provider: ^1.0.3
  #dropdown_formfield: ^0.1.4
  http: ^0.13.4
  lottie: ^1.3.0
  carousel_slider: ^4.1.1
  file_picker: ^5.2.4
  image_picker: ^0.8.6+1
  shared_preferences: ^2.0.13
  flutter_rating_bar: ^4.0.0
  path_provider: ^2.0.9
  country_picker: ^2.0.11
  intl: ^0.17.0
  pin_code_fields: ^8.0.1
  # webview_flutter: ^3.0.1
  url_launcher: ^6.0.20
  flutter_widget_from_html: ^0.15.0
  font_awesome_flutter: ^10.4.0
  share_plus: ^4.0.6
  animated_bottom_navigation_bar: ^0.3.2
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  package_info_plus: ^4.0.2
  octo_image: ^2.0.0
  bottom_navy_bar: ^6.0.0
  simple_animations: ^4.2.0
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.0.0+2
  firebase_messaging: ^14.2.0
  flutter_local_notifications: ^13.0.0
  firebase_analytics: ^10.0.8
  firebase_core: ^2.4.0
  awesome_dialog: ^3.0.2
  circular_countdown_timer: ^0.2.3
  dio: ^5.4.3+1
  otp_timer_button: ^1.1.0
  percent_indicator: ^4.2.2
  connectivity_plus: ^3.0.3
  permission_handler: ^10.2.0
  flutter_inappwebview: ^5.7.2+3
  loading_animation_widget: ^1.2.0+4
  google_sign_in: ^6.2.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0

  webview_flutter: any
  uuid: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/menu/
    - assets/images/app_logo/
    - assets/images/common/
    - assets/images/transfer/
    - assets/images/social/
    - assets/icons/
    - assets/animation/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Mulish
      fonts:
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700
